### ISSUE TITLE
NAN for very clean signal

### ISSUE THREAD

**Issue by arshak** [JuliaDSP/Estimation.jl#2]
The code returns NAN when applied to this filtered discrete dataset.  

![screen shot 2015-02-12 at 7 23 22 am](https://cloud.githubusercontent.com/assets/21704/6167335/48c883fe-b288-11e4-896b-f08979e98fda.png)

**Comment by codles** [comment]
Hi @arshak 
Which code are you referring to? Could you provide your script that produces NANs so we can try and fix the problem.

**Comment by codles** [comment]
I am closing this issue unless we have more information. Please reopen if its still an issue.
